# Generated by Django 5.2.12 on 2026-06-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_seed_default_cost_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetcostentry',
            name='selected_quote_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='orçamento selecionado'),
        ),
        migrations.AlterField(
            model_name='budgetcostentry',
            name='title',
            field=models.CharField(max_length=255, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='budgetcostquote',
            name='quote_number',
            field=models.PositiveSmallIntegerField(verbose_name='orçamento'),
        ),
        migrations.AlterField(
            model_name='budgetquote',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='preço'),
        ),
        migrations.AlterField(
            model_name='budgetquote',
            name='quote_number',
            field=models.PositiveSmallIntegerField(verbose_name='orçamento'),
        ),
        migrations.AlterField(
            model_name='budgetsection',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='budgetsection',
            name='description',
            field=models.TextField(blank=True, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='budgetsection',
            name='title',
            field=models.CharField(max_length=255, verbose_name='título'),
        ),
    ]
