# Generated by Django 5.2.12 on 2026-06-05 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_normalize_ptbr_texts'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('cadastro', 'Cadastro'), ('alteracao', 'Alteração'), ('exclusao', 'Exclusão')], max_length=20, verbose_name='ação')),
                ('target_type', models.CharField(max_length=100, verbose_name='tipo do registro')),
                ('target_name', models.CharField(max_length=255, verbose_name='registro')),
                ('description', models.TextField(blank=True, verbose_name='detalhes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
