# Generated by Django 5.2.12 on 2026-06-05 21:12

from django.db import migrations, models


def seed_calculation_roles(apps, schema_editor):
    CostField = apps.get_model('accounts', 'CostField')

    for field in CostField.objects.all():
        normalized = field.name.lower().strip()
        role = 'nenhuma'

        if 'selecionar' in normalized and 'orça' in normalized:
            role = 'orcamento_selecionado'
        elif normalized in ('preço', 'preco', 'price'):
            role = 'preco_unitario'
        elif normalized == 'quantidade':
            role = 'multiplicador'
        elif normalized == 'frete':
            role = 'frete'
        elif normalized in ('total', 'preço total', 'preco total', 'valor total'):
            role = 'total_calculado'

        if field.calculation_role != role:
            field.calculation_role = role
            field.save(update_fields=['calculation_role'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_allowedsignupemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='costfield',
            name='calculation_role',
            field=models.CharField(
                choices=[
                    ('nenhuma', 'Sem função'),
                    ('preco_unitario', 'Preço unitário'),
                    ('multiplicador', 'Multiplicador / Quantidade'),
                    ('frete', 'Frete / Adicional'),
                    ('orcamento_selecionado', 'Seletor de orçamento'),
                    ('total_calculado', 'Total calculado'),
                ],
                default='nenhuma',
                max_length=30,
                verbose_name='função de cálculo',
            ),
        ),
        migrations.RunPython(seed_calculation_roles, migrations.RunPython.noop),
    ]
