# Generated by Django 5.2.12 on 2026-06-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_sanitize_tracking_params_from_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='costfield',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
    ]
